import type {
  HeaderEntry,
  HeaderCategory,
  SecurityFinding,
  SeoFinding,
  CacheFinding,
  CorsFinding,
  CookieInfo,
  CookieFinding,
  CspAnalysis,
  CspDirective,
  HstsAnalysis,
  AnalysisResult,
} from "./types";
import { fetchUrl } from "./fetcher";
import { validateUrl } from "./ssrf";

const HEADER_CATEGORIES: Record<string, HeaderCategory> = {
  date: "general", server: "general", via: "general", connection: "general", "keep-alive": "general",
  "content-type": "response", "content-length": "response", "content-encoding": "response",
  "transfer-encoding": "response", "content-language": "response", "content-location": "response",
  "cache-control": "caching", expires: "caching", etag: "caching", "last-modified": "caching",
  age: "caching", vary: "caching", pragma: "caching",
  "strict-transport-security": "security", "content-security-policy": "security",
  "content-security-policy-report-only": "security", "x-content-type-options": "security",
  "x-frame-options": "security", "referrer-policy": "security", "permissions-policy": "security",
  "cross-origin-opener-policy": "security", "cross-origin-resource-policy": "security",
  "cross-origin-embedder-policy": "security", "x-xss-protection": "security",
  "access-control-allow-origin": "cors", "access-control-allow-credentials": "cors",
  "access-control-allow-methods": "cors", "access-control-allow-headers": "cors",
  "access-control-expose-headers": "cors", "access-control-max-age": "cors",
  "set-cookie": "cookies", location: "redirect", "x-robots-tag": "seo", link: "seo",
  "x-cache": "cdn", "cf-cache-status": "cdn", "x-served-by": "cdn",
  "x-powered-by": "cdn", "x-aspnet-version": "cdn", "x-aspnetmvc-version": "cdn",
};

const HEADER_DESCRIPTIONS: Record<string, string> = {
  date: "Date and time the response was generated",
  server: "Software used by the server to handle requests",
  via: "Intermediaries (proxies, gateways) between client and server",
  connection: "Connection management directives",
  "keep-alive": "Keep-alive timeout parameters",
  "content-type": "Media type and charset of the response body",
  "content-length": "Size of the response body in bytes",
  "content-encoding": "Compression algorithm used for the response body",
  "transfer-encoding": "Transfer encoding applied to the message body",
  "content-language": "Natural language of the response content",
  "content-location": "Alternative location for the response content",
  "cache-control": "Caching directives for the response",
  expires: "Date/time after which the response is considered stale",
  etag: "Entity tag for cache validation",
  "last-modified": "Date/time the resource was last modified",
  age: "Time in seconds since the response was generated by the origin",
  vary: "Request headers that affect the response representation",
  pragma: "Implementation-specific directives",
  "strict-transport-security": "Instructs browsers to use HTTPS for future connections",
  "content-security-policy": "Defines allowed sources for content loading",
  "content-security-policy-report-only": "CSP policy in report-only mode (not enforced)",
  "x-content-type-options": "Prevents MIME-type sniffing",
  "x-frame-options": "Controls whether the page can be embedded in iframes",
  "referrer-policy": "Controls how much referrer information is sent with requests",
  "permissions-policy": "Controls which browser features are allowed",
  "cross-origin-opener-policy": "Isolates browsing context for cross-origin documents",
  "cross-origin-resource-policy": "Controls how resources can be loaded cross-origin",
  "cross-origin-embedder-policy": "Requires opt-in for cross-origin resource loading",
  "x-xss-protection": "Enables XSS filtering in older browsers (deprecated)",
  "access-control-allow-origin": "Origins allowed to access the resource via CORS",
  "access-control-allow-credentials": "Whether credentials can be sent in CORS requests",
  "access-control-allow-methods": "HTTP methods allowed in CORS requests",
  "access-control-allow-headers": "Headers allowed in CORS requests",
  "access-control-expose-headers": "Headers the browser can read from the response",
  "access-control-max-age": "How long preflight responses can be cached",
  "set-cookie": "Sets a cookie on the client",
  location: "URL to redirect to (used with 3xx status codes)",
  "x-robots-tag": "HTTP-level robots directives for crawlers",
  link: "Related resources (canonical URLs, preloads, etc.)",
  "x-cache": "Cache hit/miss status from CDN or proxy",
  "cf-cache-status": "Cloudflare cache status",
  "x-served-by": "Server or CDN node handling the request",
  "x-powered-by": "Technology stack behind the application",
  "x-aspnet-version": "ASP.NET version",
  "x-aspnetmvc-version": "ASP.NET MVC version",
};

function categorizeHeader(name: string): HeaderCategory {
  return HEADER_CATEGORIES[name.toLowerCase()] || "unknown";
}

function describeHeader(name: string): string {
  return HEADER_DESCRIPTIONS[name.toLowerCase()] || "HTTP response header";
}

function parseCookies(headers: Record<string, string>): CookieInfo[] {
  const cookies: CookieInfo[] = [];
  const setCookieValue = headers["set-cookie"];
  if (!setCookieValue) return cookies;

  // Set-Cookie values are joined with null byte delimiter
  const setCookieHeaders = setCookieValue.split("\x00");

  for (const cookieStr of setCookieHeaders) {
    const parts = cookieStr.split(";").map((p) => p.trim());
    if (parts.length === 0) continue;

    const [nameValue, ...attributeParts] = parts;
    const eqIdx = nameValue.indexOf("=");
    if (eqIdx < 0) continue;

    const name = nameValue.slice(0, eqIdx).trim();
    const value = nameValue.slice(eqIdx + 1).trim();

    const attrs: Record<string, string> = {};
    let domain: string | null = null;
    let path: string | null = null;
    let expires: string | null = null;
    let maxAge: number | null = null;
    let secure = false;
    let httpOnly = false;
    let sameSite: string | null = null;

    for (const attr of attributeParts) {
      const aEqIdx = attr.indexOf("=");
      if (aEqIdx > 0) {
        const attrName = attr.slice(0, aEqIdx).trim().toLowerCase();
        const attrValue = attr.slice(aEqIdx + 1).trim();
        attrs[attrName] = attrValue;
        if (attrName === "domain") domain = attrValue;
        else if (attrName === "path") path = attrValue;
        else if (attrName === "expires") expires = attrValue;
        else if (attrName === "max-age") maxAge = parseInt(attrValue, 10);
        else if (attrName === "samesite") sameSite = attrValue;
      } else {
        const attrName = attr.trim().toLowerCase();
        attrs[attrName] = "";
        if (attrName === "secure") secure = true;
        else if (attrName === "httponly") httpOnly = true;
        else if (attrName === "samesite") sameSite = "Strict";
      }
    }

    cookies.push({ name, value, domain, path, expires, maxAge, secure, httpOnly, sameSite, attributes: attrs });
  }

  return cookies;
}

function analyzeCookies(cookies: CookieInfo[]): CookieFinding[] {
  return cookies.map((cookie) => {
    const observations: string[] = [];

    if (cookie.secure) {
      observations.push("Cookie has the Secure attribute — it will only be sent over HTTPS.");
    } else {
      observations.push("Cookie does not have the Secure attribute — it may be sent over unencrypted connections.");
    }

    if (cookie.httpOnly) {
      observations.push("Cookie has the HttpOnly attribute — it is not accessible via JavaScript.");
    } else {
      observations.push("Cookie does not have the HttpOnly attribute — it is accessible via JavaScript.");
    }

    if (cookie.sameSite) {
      if (cookie.sameSite === "None") {
        if (cookie.secure) {
          observations.push("SameSite=None with Secure — cookie allows cross-site requests but requires HTTPS.");
        } else {
          observations.push("SameSite=None without Secure — browsers may reject this cookie in modern versions.");
        }
      } else if (cookie.sameSite === "Strict") {
        observations.push("SameSite=Strict — cookie is only sent for same-site requests.");
      } else if (cookie.sameSite === "Lax") {
        observations.push("SameSite=Lax — cookie is sent for same-site requests and top-level navigations.");
      }
    } else {
      observations.push("No SameSite attribute — browsers default to Lax behavior.");
    }

    if (cookie.domain) {
      observations.push(`Cookie is scoped to domain: ${cookie.domain}`);
    }
    if (cookie.path && cookie.path !== "/") {
      observations.push(`Cookie is scoped to path: ${cookie.path}`);
    }
    if (cookie.expires) {
      observations.push(`Cookie expires: ${cookie.expires}`);
    }
    if (cookie.maxAge !== null) {
      observations.push(`Cookie max-age: ${cookie.maxAge} seconds`);
    }

    return { cookie, observations };
  });
}

function parseCsp(value: string): CspDirective[] {
  const directives: CspDirective[] = [];
  const parts = value.split(";");
  for (const part of parts) {
    const trimmed = part.trim();
    if (!trimmed) continue;
    const spaceIdx = trimmed.indexOf(" ");
    if (spaceIdx < 0) {
      directives.push({ name: trimmed, values: [] });
    } else {
      const name = trimmed.slice(0, spaceIdx).toLowerCase();
      const values = trimmed.slice(spaceIdx + 1).trim().split(/\s+/);
      directives.push({ name, values });
    }
  }
  return directives;
}

function analyzeCsp(value: string, isReportOnly: boolean): CspAnalysis {
  const directives = parseCsp(value);
  const hasUnsafeInline = directives.some((d) => d.values.includes("'unsafe-inline'"));
  const hasUnsafeEval = directives.some((d) => d.values.includes("'unsafe-eval'"));
  const hasWildcard = directives.some((d) => d.values.includes("*"));
  const observations: string[] = [];

  if (isReportOnly) {
    observations.push("This is a Content-Security-Policy-Report-Only header — the policy is not enforced. It is used for testing and reporting.");
  } else {
    observations.push("Content-Security-Policy is active — the browser enforces this policy.");
  }

  if (hasUnsafeInline) {
    observations.push("'unsafe-inline' is present — inline scripts/styles are permitted by this policy, which may reduce CSP protection against XSS.");
  }
  if (hasUnsafeEval) {
    observations.push("'unsafe-eval' is present — eval() and similar code execution is permitted by this policy.");
  }
  if (hasWildcard) {
    observations.push("'*' wildcard source is present — resources can be loaded from any origin.");
  }

  const scriptSrc = directives.find((d) => d.name === "script-src");
  if (scriptSrc && !hasUnsafeInline && !hasUnsafeEval && !hasWildcard) {
    observations.push("script-src restricts script sources without unsafe-inline or unsafe-eval.");
  }

  const frameAncestors = directives.find((d) => d.name === "frame-ancestors");
  if (frameAncestors) {
    if (frameAncestors.values.includes("'none'")) {
      observations.push("frame-ancestors 'none' — the page cannot be embedded in any frame or iframe.");
    } else if (frameAncestors.values.includes("'self'")) {
      observations.push("frame-ancestors 'self' — the page can only be embedded by same-origin frames.");
    } else {
      observations.push(`frame-ancestors allows specific origins: ${frameAncestors.values.join(", ")}`);
    }
  }

  const baseUri = directives.find((d) => d.name === "base-uri");
  if (baseUri && baseUri.values.includes("'self'")) {
    observations.push("base-uri 'self' — restricts the base URL for the document.");
  }

  const formAction = directives.find((d) => d.name === "form-action");
  if (formAction) {
    observations.push(`form-action restricts where forms can submit to: ${formAction.values.join(", ")}`);
  }

  if (!directives.find((d) => d.name === "default-src") && !scriptSrc) {
    observations.push("No default-src or script-src directive found.");
  }

  return { directives, hasUnsafeInline, hasUnsafeEval, hasWildcard, isReportOnly, observations };
}

function analyzeHsts(value: string | null): HstsAnalysis | null {
  if (!value) return null;

  const directives = value.split(";").map((d) => d.trim().toLowerCase());
  let maxAge: number | null = null;
  let includeSubDomains = false;
  let preload = false;
  const observations: string[] = [];

  for (const dir of directives) {
    if (dir.startsWith("max-age=")) {
      maxAge = parseInt(dir.split("=")[1], 10);
    } else if (dir === "includesubdomains") {
      includeSubDomains = true;
    } else if (dir === "preload") {
      preload = true;
    }
  }

  if (maxAge === null || isNaN(maxAge)) {
    observations.push("HSTS header is present but does not contain a valid max-age value.");
  } else if (maxAge === 0) {
    observations.push("max-age is 0 — HSTS is effectively disabled. Browsers will not enforce HTTPS for this site.");
  } else if (maxAge < 31536000) {
    observations.push(`max-age is ${maxAge} — a value of at least 31536000 (one year) is generally recommended for HSTS.`);
  } else {
    observations.push(`max-age is ${maxAge} — the browser will enforce HTTPS for this duration in seconds.`);
  }

  if (includeSubDomains) {
    observations.push("includeSubDomains is set — the HSTS policy applies to all subdomains.");
  }
  if (preload) {
    if (maxAge && maxAge >= 31536000 && includeSubDomains) {
      observations.push("preload is set with sufficient max-age and includeSubDomains — this site may qualify for HSTS preload lists.");
    } else {
      observations.push("preload is set, but the policy may not meet HSTS preload requirements (needs max-age >= 31536000 and includeSubDomains).");
    }
  }

  return { maxAge, includeSubDomains, preload, directives, observations };
}

function analyzeSecurity(headers: Record<string, string>, cspAnalysis: CspAnalysis | null, hstsAnalysis: HstsAnalysis | null): SecurityFinding[] {
  const findings: SecurityFinding[] = [];

  // HSTS
  const hsts = headers["strict-transport-security"];
  if (hsts) {
    findings.push({
      header: "Strict-Transport-Security",
      status: "present",
      value: hsts,
      explanation: hstsAnalysis?.observations.join(" ") || "HSTS header is present.",
      severity: "high",
    });
  } else {
    findings.push({
      header: "Strict-Transport-Security",
      status: "missing",
      value: null,
      explanation: "HSTS header is not present. HSTS can instruct browsers to use HTTPS for future connections to this site.",
      severity: "medium",
    });
  }

  // CSP
  const csp = headers["content-security-policy"];
  const cspReportOnly = headers["content-security-policy-report-only"];
  if (csp) {
    findings.push({
      header: "Content-Security-Policy",
      status: "configured",
      value: csp.length > 200 ? csp.slice(0, 200) + "..." : csp,
      explanation: cspAnalysis?.observations.join(" ") || "CSP header is present.",
      severity: cspAnalysis?.hasUnsafeInline || cspAnalysis?.hasUnsafeEval ? "medium" : "low",
    });
  } else if (cspReportOnly) {
    findings.push({
      header: "Content-Security-Policy-Report-Only",
      status: "needs-review",
      value: cspReportOnly.length > 200 ? cspReportOnly.slice(0, 200) + "..." : cspReportOnly,
      explanation: "Only a report-only CSP policy is present. The policy is not enforced by the browser.",
      severity: "informational",
    });
  } else {
    findings.push({
      header: "Content-Security-Policy",
      status: "missing",
      value: null,
      explanation: "No Content-Security-Policy header is present. A CSP can help protect against XSS and data injection attacks.",
      severity: "medium",
    });
  }

  // X-Content-Type-Options
  const xcto = headers["x-content-type-options"];
  if (xcto) {
    const nosniff = xcto.toLowerCase().includes("nosniff");
    findings.push({
      header: "X-Content-Type-Options",
      status: nosniff ? "configured" : "needs-review",
      value: xcto,
      explanation: nosniff
        ? "nosniff prevents the browser from MIME-type sniffing the response content type."
        : `Value '${xcto}' is not the standard 'nosniff' value.`,
      severity: nosniff ? "low" : "medium",
    });
  } else {
    findings.push({
      header: "X-Content-Type-Options",
      status: "missing",
      value: null,
      explanation: "Header is not present. Without nosniff, the browser may perform MIME-type sniffing.",
      severity: "low",
    });
  }

  // X-Frame-Options
  const xfo = headers["x-frame-options"];
  const hasFrameAncestors = cspAnalysis?.directives.some((d) => d.name === "frame-ancestors");
  if (xfo) {
    const valid = ["deny", "sameorigin"].includes(xfo.toLowerCase());
    findings.push({
      header: "X-Frame-Options",
      status: valid ? "configured" : "needs-review",
      value: xfo,
      explanation: valid
        ? `${xfo} controls whether the page can be embedded in frames.`
        : `Value '${xfo}' is not a standard value. Expected DENY or SAMEORIGIN.`,
      severity: valid ? "low" : "medium",
    });
  } else if (hasFrameAncestors) {
    findings.push({
      header: "X-Frame-Options",
      status: "informational",
      value: null,
      explanation: "X-Frame-Options is not present, but a frame-ancestors directive exists in the Content-Security-Policy, which provides similar protection.",
      severity: "informational",
    });
  } else {
    findings.push({
      header: "X-Frame-Options",
      status: "missing",
      value: null,
      explanation: "Header is not present. Without X-Frame-Options or CSP frame-ancestors, the page may be embeddable in iframes.",
      severity: "low",
    });
  }

  // Referrer-Policy
  const rp = headers["referrer-policy"];
  if (rp) {
    findings.push({
      header: "Referrer-Policy",
      status: "configured",
      value: rp,
      explanation: `Referrer-Policy is set to '${rp}', controlling how much referrer information is sent with requests.`,
      severity: "informational",
    });
  } else {
    findings.push({
      header: "Referrer-Policy",
      status: "missing",
      value: null,
      explanation: "Header is not present. Browsers may send full referrer information by default.",
      severity: "low",
    });
  }

  // Permissions-Policy
  const pp = headers["permissions-policy"];
  if (pp) {
    findings.push({
      header: "Permissions-Policy",
      status: "configured",
      value: pp.length > 150 ? pp.slice(0, 150) + "..." : pp,
      explanation: "Permissions-Policy controls which browser features are allowed. The policy restricts access to specified APIs.",
      severity: "informational",
    });
  } else {
    findings.push({
      header: "Permissions-Policy",
      status: "missing",
      value: null,
      explanation: "Header is not present. Without Permissions-Policy, the browser uses its default feature permissions.",
      severity: "informational",
    });
  }

  // COOP
  const coop = headers["cross-origin-opener-policy"];
  if (coop) {
    findings.push({
      header: "Cross-Origin-Opener-Policy",
      status: "configured",
      value: coop,
      explanation: `COOP is set to '${coop}', isolating the browsing context for cross-origin documents.`,
      severity: "informational",
    });
  }

  // CORP
  const corp = headers["cross-origin-resource-policy"];
  if (corp) {
    findings.push({
      header: "Cross-Origin-Resource-Policy",
      status: "configured",
      value: corp,
      explanation: `CORP is set to '${corp}', controlling how this resource can be loaded cross-origin.`,
      severity: "informational",
    });
  }

  // COEP
  const coep = headers["cross-origin-embedder-policy"];
  if (coep) {
    findings.push({
      header: "Cross-Origin-Embedder-Policy",
      status: "configured",
      value: coep,
      explanation: `COEP is set to '${coep}', requiring opt-in for cross-origin resource loading.`,
      severity: "informational",
    });
  }

  return findings;
}

function analyzeSeo(headers: Record<string, string>, finalUrl: string, statusCode: number, redirectCount: number): SeoFinding[] {
  const findings: SeoFinding[] = [];

  const robotsTag = headers["x-robots-tag"];
  if (robotsTag) {
    const directives = robotsTag.toLowerCase();
    const parts = directives.split(",").map((p) => p.trim());
    const hasNoindex = parts.includes("noindex");
    const hasNofollow = parts.includes("nofollow");

    findings.push({
      header: "X-Robots-Tag",
      status: hasNoindex ? "needs-review" : "configured",
      value: robotsTag,
      explanation: hasNoindex
        ? `X-Robots-Tag contains 'noindex' — search engines may be instructed not to index this page.`
        : hasNofollow
          ? `X-Robots-Tag contains 'nofollow' — search engines may be instructed not to follow links on this page.`
          : `X-Robots-Tag provides HTTP-level robots directives for crawlers.`,
    });
  } else {
    findings.push({
      header: "X-Robots-Tag",
      status: "informational",
      value: null,
      explanation: "No X-Robots-Tag header is present. This does not affect indexing — robots directives can also be set via HTML meta tags.",
    });
  }

  const link = headers["link"];
  if (link) {
    const canonicalMatch = link.match(/<[^>]+>;\s*rel="canonical"/i);
    if (canonicalMatch) {
      const urlMatch = canonicalMatch[0].match(/<([^>]+)>/);
      findings.push({
        header: "Link (canonical)",
        status: "configured",
        value: urlMatch?.[1] || link,
        explanation: "A canonical Link header is present, indicating the preferred URL for this content.",
      });
    }
  }

  const isHttps = finalUrl.startsWith("https://");
  if (isHttps) {
    findings.push({
      header: "HTTPS",
      status: "configured",
      value: "Yes",
      explanation: "The final response is served over HTTPS.",
    });
  } else {
    findings.push({
      header: "HTTPS",
      status: "needs-review",
      value: "No",
      explanation: "The final response is served over HTTP. HTTPS is recommended for all public websites.",
    });
  }

  if (statusCode >= 200 && statusCode < 300) {
    findings.push({
      header: "Status Code",
      status: "configured",
      value: `${statusCode}`,
      explanation: `The request returned a successful ${statusCode} status code.`,
    });
  } else if (statusCode >= 300 && statusCode < 400) {
    findings.push({
      header: "Status Code",
      status: "informational",
      value: `${statusCode}`,
      explanation: `The request returned a redirect (${statusCode}) status code.`,
    });
  } else if (statusCode >= 400) {
    findings.push({
      header: "Status Code",
      status: "needs-review",
      value: `${statusCode}`,
      explanation: `The request returned a ${statusCode} error status code.`,
    });
  }

  if (redirectCount > 0) {
    findings.push({
      header: "Redirect Chain",
      status: redirectCount > 3 ? "needs-review" : "informational",
      value: `${redirectCount} redirect${redirectCount !== 1 ? "s" : ""}`,
      explanation: redirectCount > 3
        ? `The redirect chain contains ${redirectCount} hops. Long redirect chains can slow page loads and may cause issues for search engine crawlers.`
        : `The request followed ${redirectCount} redirect${redirectCount !== 1 ? "s" : ""} before reaching the final URL.`,
    });
  }

  return findings;
}

function analyzeCache(headers: Record<string, string>): CacheFinding[] {
  const findings: CacheFinding[] = [];

  const cacheControl = headers["cache-control"];
  if (cacheControl) {
    const directives = cacheControl.toLowerCase().split(",").map((d) => d.trim());
    const hasNoStore = directives.includes("no-store");
    const hasNoCache = directives.includes("no-cache");
    const hasPublic = directives.includes("public");
    const hasPrivate = directives.includes("private");
    const maxAgeMatch = cacheControl.match(/max-age=(\d+)/);
    const sMaxAgeMatch = cacheControl.match(/s-maxage=(\d+)/);

    let explanation = "Cache-Control contains: ";
    const parts: string[] = [];

    if (hasNoStore) parts.push("no-store (response should not be cached)");
    if (hasNoCache) parts.push("no-cache (stored responses must be revalidated before use)");
    if (hasPublic) parts.push("public (response may be cached by any cache)");
    if (hasPrivate) parts.push("private (response may only be cached by the browser)");
    if (maxAgeMatch) parts.push(`max-age=${maxAgeMatch[1]} (fresh for ${maxAgeMatch[1]} seconds)`);
    if (sMaxAgeMatch) parts.push(`s-maxage=${sMaxAgeMatch[1]} (shared cache max-age)`);

    explanation += parts.join(", ") || cacheControl;

    findings.push({
      header: "Cache-Control",
      status: "configured",
      value: cacheControl,
      explanation,
    });
  } else {
    findings.push({
      header: "Cache-Control",
      status: "missing",
      value: null,
      explanation: "No Cache-Control header is present. The browser may use heuristic caching based on other headers.",
    });
  }

  const expires = headers["expires"];
  if (expires) {
    const expDate = new Date(expires);
    const now = new Date();
    const isExpired = expDate < now;
    findings.push({
      header: "Expires",
      status: "configured",
      value: expires,
      explanation: isExpired
        ? "The Expires header indicates the response is already stale."
        : `The Expires header indicates when the response becomes stale: ${expires}`,
    });
  }

  const etag = headers["etag"];
  if (etag) {
    const isWeak = etag.startsWith("W/");
    findings.push({
      header: "ETag",
      status: "configured",
      value: etag,
      explanation: isWeak
        ? `ETag is a weak validator (${etag}). Weak ETags are used for semantic equivalence comparison.`
        : `ETag is a strong validator (${etag}), used for cache validation.`,
    });
  }

  const lastModified = headers["last-modified"];
  if (lastModified) {
    findings.push({
      header: "Last-Modified",
      status: "configured",
      value: lastModified,
      explanation: `The resource was last modified on ${lastModified}.`,
    });
  }

  const vary = headers["vary"];
  if (vary) {
    const varyHeaders = vary.split(",").map((h) => h.trim());
    findings.push({
      header: "Vary",
      status: "configured",
      value: vary,
      explanation: `The response varies based on: ${varyHeaders.join(", ")}. Caches must store separate representations for different values of these headers.`,
    });
  }

  const age = headers["age"];
  if (age) {
    const ageSeconds = parseInt(age, 10);
    findings.push({
      header: "Age",
      status: "configured",
      value: age,
      explanation: `The response is approximately ${ageSeconds} seconds old in the cache.`,
    });
  }

  return findings;
}

function analyzeCors(headers: Record<string, string>): CorsFinding[] {
  const findings: CorsFinding[] = [];
  const acao = headers["access-control-allow-origin"];
  const acac = headers["access-control-allow-credentials"];

  if (acao) {
    if (acao === "*") {
      if (acac?.toLowerCase() === "true") {
        findings.push({
          header: "Access-Control-Allow-Origin",
          status: "needs-review",
          value: acao,
          explanation: "Wildcard (*) origin with Access-Control-Allow-Credentials: true is an invalid combination in the browser CORS model. Browsers will reject credentialed requests with a wildcard origin. This configuration may cause CORS failures.",
        });
      } else {
        findings.push({
          header: "Access-Control-Allow-Origin",
          status: "configured",
          value: acao,
          explanation: "Wildcard (*) origin allows any website to access the resource via CORS. Credentials are not supported with wildcard origins.",
        });
      }
    } else {
      findings.push({
        header: "Access-Control-Allow-Origin",
        status: "configured",
        value: acao,
        explanation: `CORS access is restricted to the origin: ${acao}`,
      });
    }
  } else {
    findings.push({
      header: "Access-Control-Allow-Origin",
      status: "informational",
      value: null,
      explanation: "No CORS headers are present. Cross-origin requests from browsers will be blocked by the Same-Origin Policy.",
    });
  }

  if (acac) {
    findings.push({
      header: "Access-Control-Allow-Credentials",
      status: "configured",
      value: acac,
      explanation: `Credentials are ${acac.toLowerCase() === "true" ? "allowed" : "not allowed"} in cross-origin requests.`,
    });
  }

  const acam = headers["access-control-allow-methods"];
  if (acam) {
    findings.push({
      header: "Access-Control-Allow-Methods",
      status: "configured",
      value: acam,
      explanation: `Allowed HTTP methods for cross-origin requests: ${acam}`,
    });
  }

  const acah = headers["access-control-allow-headers"];
  if (acah) {
    findings.push({
      header: "Access-Control-Allow-Headers",
      status: "configured",
      value: acah,
      explanation: `Allowed request headers for cross-origin requests: ${acah}`,
    });
  }

  const acean = headers["access-control-expose-headers"];
  if (acean) {
    findings.push({
      header: "Access-Control-Expose-Headers",
      status: "configured",
      value: acean,
      explanation: `Response headers accessible to the browser: ${acean}`,
    });
  }

  const acma = headers["access-control-max-age"];
  if (acma) {
    findings.push({
      header: "Access-Control-Max-Age",
      status: "configured",
      value: acma,
      explanation: `Preflight responses can be cached for ${acma} seconds.`,
    });
  }

  return findings;
}

function buildHeaderEntries(headers: Record<string, string>): HeaderEntry[] {
  return Object.entries(headers).map(([name, value]) => ({
    name,
    value,
    category: categorizeHeader(name),
    description: describeHeader(name),
    importance: "informational" as const,
  }));
}

function buildRawHeaders(headers: Record<string, string>, httpVersion: string | null, statusCode: number, statusText: string): string {
  const lines: string[] = [];
  lines.push(`${httpVersion || "HTTP/1.1"} ${statusCode} ${statusText}`);
  for (const [name, value] of Object.entries(headers)) {
    lines.push(`${name}: ${value}`);
  }
  return lines.join("\n");
}

export async function analyzeHttpHeaders(inputUrl: string): Promise<AnalysisResult> {
  const validation = validateUrl(inputUrl);
  if (!validation.valid || !validation.url) {
    return {
      requestedUrl: inputUrl,
      finalUrl: "",
      statusCode: 0,
      statusText: "",
      httpVersion: null,
      responseTimeMs: 0,
      redirectCount: 0,
      redirectChain: [],
      contentType: null,
      contentLength: null,
      server: null,
      date: null,
      headers: {},
      headerEntries: [],
      securityFindings: [],
      seoFindings: [],
      cacheFindings: [],
      corsFindings: [],
      cookieFindings: [],
      cspAnalysis: null,
      hstsAnalysis: null,
      error: { code: "INVALID_URL", message: validation.error || "Invalid URL" },
    };
  }

  const targetUrl = validation.url.href;
  const fetchResult = await fetchUrl(targetUrl, "GET");

  if (fetchResult.error) {
    return {
      requestedUrl: inputUrl,
      finalUrl: fetchResult.finalUrl,
      statusCode: fetchResult.statusCode,
      statusText: fetchResult.statusText,
      httpVersion: fetchResult.httpVersion,
      responseTimeMs: fetchResult.responseTimeMs,
      redirectCount: fetchResult.redirectChain.length,
      redirectChain: fetchResult.redirectChain,
      contentType: null,
      contentLength: null,
      server: null,
      date: null,
      headers: {},
      headerEntries: [],
      securityFindings: [],
      seoFindings: [],
      cacheFindings: [],
      corsFindings: [],
      cookieFindings: [],
      cspAnalysis: null,
      hstsAnalysis: null,
      error: fetchResult.error,
    };
  }

  const cookies = parseCookies(fetchResult.headers);
  const cspValue = fetchResult.headers["content-security-policy"];
  const cspReportOnlyValue = fetchResult.headers["content-security-policy-report-only"];
  const cspAnalysis = cspValue ? analyzeCsp(cspValue, false) : cspReportOnlyValue ? analyzeCsp(cspReportOnlyValue, true) : null;
  const hstsAnalysis = analyzeHsts(fetchResult.headers["strict-transport-security"]);

  return {
    requestedUrl: inputUrl,
    finalUrl: fetchResult.finalUrl,
    statusCode: fetchResult.statusCode,
    statusText: fetchResult.statusText,
    httpVersion: fetchResult.httpVersion,
    responseTimeMs: fetchResult.responseTimeMs,
    redirectCount: fetchResult.redirectChain.length,
    redirectChain: fetchResult.redirectChain,
    contentType: fetchResult.contentType,
    contentLength: fetchResult.contentLength,
    server: fetchResult.server,
    date: fetchResult.date,
    headers: fetchResult.headers,
    headerEntries: buildHeaderEntries(fetchResult.headers),
    securityFindings: analyzeSecurity(fetchResult.headers, cspAnalysis, hstsAnalysis),
    seoFindings: analyzeSeo(fetchResult.headers, fetchResult.finalUrl, fetchResult.statusCode, fetchResult.redirectChain.length),
    cacheFindings: analyzeCache(fetchResult.headers),
    corsFindings: analyzeCors(fetchResult.headers),
    cookieFindings: analyzeCookies(cookies),
    cspAnalysis,
    hstsAnalysis,
    error: null,
  };
}

export { buildRawHeaders };
